version: '3.8'

services:
  backend:
    platform: linux/x86_64
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    command: uvicorn main:app --reload
