version: '3.8'

services:
  backend:
    platform: linux/x86_64
    # When the physical robot is be used, the ports will be uncommented and we need confirgure the robot's to listen this
    # ports:
    #   - 8000:8000
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    command: python3 main.py
